### ISSUE TITLE
Assembly generation issues

### ISSUE THREAD

**Issue by tergav17** [EtchedPixels/CenturionTools#1]
A couple of instruction generation issues I noticed while using the assembler.

#1: `XFR BL,AL` generates BL <- AL instead of AL <- BL, making it functionally the same as `XFR AL,BL`

#2: `ORI AL,BL` generates the opcode "4B", which transfers AL into XL instead of an inclusive OR operation.

Thanks

**Comment by EtchedPixels** [comment]
Should be fixed now
